### PR TITLE
Add support for `force_verify`

### PR DESCRIPTION
**Pull request by maxtruxa**
Adds support for the `force_verify` option as shown in the [official documentation](https://github.com/justintv/Twitch-API/blob/master/authentication.md#authorization-code-flow).

### CODE REVIEW

**Comment by Schmoopiie** [comment]
Will push your PR and push the update on npm this weekend, thank you :+1:

**Comment by jbuerkel** [comment]
Any news regarding this PR?

**Comment by Schmoopiie** [comment]
Can't believe I forgot to update this, my bad :unamused:

**Comment by Schmoopiie** [comment]
There you go, also updated on npm.

**Pull request merged**
